yarnPath: "./.yarn/releases/yarn-4.0.2.cjs"

# We don't use Zero Install: compression level defaults to 0 (no compression) in yarn 4
# because 0 (no compression) is slightly better for git. As we don't commit the packages,
# we continue to use the yarn 3 default compression mode.
#
# 2024-04-25 - Appveyor suddenly failed to run the tests with:
#
# ~001 i | | | | >  [] Building '@local/ck-gen' package...
# ~001 i | | | | | >  [] Running 'yarn install' in 'C:/CKli-World/CK-Crs-Projects/CK-StObj-TypeScript/Tests/CK.StObj.TypeScript.Tests/TSTests/TypeScriptRunner_with_environment_variables_Async/ck-gen'.
# ~001 t | | | | | |  [] ➤ YN0000: · Yarn 4.0.2
# ~001 t | | | | | |  [] ➤ YN0000: ┌ Resolution step
# ~001 t | | | | | |  [] ➤ YN0000: └ Completed in 0s 308ms
# ~001 t | | | | | |  [] ➤ YN0000: ┌ Fetch step
# ~001 t | | | | | |  [] ➤ YN0001: │ Libzip Error: Zlib error: insufficient memory
# ~001 t | | | | | |  []     at ZipFS.makeLibzipError ([worker eval]:1:296669)
# ~001 t | | | | | |  []     at ZipFS.getBufferAndClose ([worker eval]:1:297436)
# ~001 t | | | | | |  []     at ZipFS.saveAndClose ([worker eval]:1:298901)
# ~001 t | | | | | |  []     at convertToZipWorker ([worker eval]:1:407821)
# ~001 t | | | | | |  []     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
# ~001 t | | | | | |  []     at async MessagePort.<anonymous> ([worker eval]:1:409593)
# ~001 t | | | | | |  [] ➤ YN0000: └ Completed in 8s 316ms
# ~001 t | | | | | |  [] ➤ YN0000: · Failed with errors in 8s 708ms
# ~001 E | | | | | |  [] 'yarn install' failed with code 1.
# ~001 i | | | | | <
# ~001 i | | | | < Failed.
#
# Replacing "mixed" by "0".
compressionLevel: 0

# We prevent Yarn to query the remote registries to validate that the lockfile 
# content matches the remote information.
enableHardenedMode: false

# cacheFolder: "./.yarn/cache", enableGlobalCache: false and enableMirror: false
# Let each repository have its local cache, independent from any global cache.
cacheFolder: "./.yarn/cache"
enableGlobalCache: false
enableMirror: false
