yarnPath: "./.yarn/releases/yarn-4.2.2.cjs"

# We don't use Zero Install: compression level defaults to 0 (no compression) in yarn 4
# because 0 (no compression) is slightly better for git. As we don't commit the packages,
# we continue to use the yarn 3 default compression mode.
#
# 2024-04-25 - Appveyor suddenly failed to run the tests. This is a node x86 vs x64 issue. The solution is to
# tell appveyor to setup the x64 version of node. This is added to appveyor.yml:
#
#   install:
#   - ps: Install-Product node 20 x64
#  
compressionLevel: mixed

# We prevent Yarn to query the remote registries to validate that the lockfile 
# content matches the remote information.
enableHardenedMode: false

# cacheFolder: "./.yarn/cache", enableGlobalCache: false and enableMirror: false
# Let each repository have its local cache, independent from any global cache.
cacheFolder: "./.yarn/cache"
enableGlobalCache: false
enableMirror: false
